import Mathlib.CategoryTheory.Category.Basic
import Mathlib.CategoryTheory.Functor.Basic
import Mathlib.Data.Real.Basic

universe u v

namespace EnergyAsContradiction.CategoryDynamics

open CategoryTheory

/-- A bundled energy system: a state space together with an energy functional. -/
structure ConstraintEnergy where
  State : Type u
  energy : State → ℝ

namespace ConstraintEnergy

/-- Morphisms are energy-nonincreasing maps. -/
structure Hom (X Y : ConstraintEnergy.{u}) where
  toFun : X.State → Y.State
  noninc : ∀ x, Y.energy (toFun x) ≤ X.energy x

attribute [coe] Hom.toFun

@[ext]
theorem Hom.ext {X Y : ConstraintEnergy.{u}} (f g : Hom X Y)
    (h : ∀ x, f.toFun x = g.toFun x) : f = g := by
  cases f
  cases g
  simp at h
  cases hfun : toFun
  cases hgun : toFun_1
  simp at h
  subst h
  rfl

/-- Identity morphism. -/
def id (X : ConstraintEnergy.{u}) : Hom X X where
  toFun := id
  noninc := by
    intro x
    rfl.le

/-- Composition of energy-nonincreasing maps. -/
def comp {X Y Z : ConstraintEnergy.{u}} (f : Hom X Y) (g : Hom Y Z) : Hom X Z where
  toFun := g.toFun ∘ f.toFun
  noninc := by
    intro x
    exact le_trans (g.noninc (f.toFun x)) (f.noninc x)

instance : Category ConstraintEnergy.{u} where
  Hom X Y := Hom X Y
  id := id
  comp f g := comp f g

@[simp] theorem id_toFun (X : ConstraintEnergy.{u}) :
    (𝟙 X : X ⟶ X).toFun = id := rfl

@[simp] theorem comp_toFun {X Y Z : ConstraintEnergy.{u}}
    (f : X ⟶ Y) (g : Y ⟶ Z) :
    (f ≫ g).toFun = g.toFun ∘ f.toFun := rfl

/-- A dynamics on an energy system is an endomorphism together with its
energy-decrease proof. -/
structure Dynamics (X : ConstraintEnergy.{u}) where
  update : X.State → X.State
  decreases : ∀ x, X.energy (update x) ≤ X.energy x

/-- Any dynamics yields an endomorphism in the category. -/
def Dynamics.toHom {X : ConstraintEnergy.{u}} (D : Dynamics X) : X ⟶ X where
  toFun := D.update
  noninc := D.decreases

@[simp] theorem Dynamics.toHom_toFun {X : ConstraintEnergy.{u}} (D : Dynamics X) :
    D.toHom.toFun = D.update := rfl

/-- A system equipped uniformly with a chosen dynamics on every object gives
an endofunctor that is identity on objects and acts by post-composition with
the update on morphisms. -/
structure DynamicFamily where
  dyn : ∀ X : ConstraintEnergy.{u}, Dynamics X

/-- The endofunctor generated by a uniform dynamic family. -/
def DynamicFamily.toFunctor (F : DynamicFamily.{u}) : ConstraintEnergy.{u} ⥤ ConstraintEnergy.{u} where
  obj X := X
  map {X Y} f :=
    { toFun := fun x => f.toFun ((F.dyn X).update x)
      noninc := by
        intro x
        exact le_trans (f.noninc ((F.dyn X).update x)) ((F.dyn X).decreases x) }
  map_id := by
    intro X
    ext x
    rfl
  map_comp := by
    intro X Y Z f g
    ext x
    rfl

/-- A convenience constructor for dynamics from any self-map with an explicit
energy monotonicity proof. -/
def mkDynamics {X : ConstraintEnergy.{u}}
    (u : X.State → X.State)
    (h : ∀ x, X.energy (u x) ≤ X.energy x) : Dynamics X where
  update := u
  decreases := h

end ConstraintEnergy

open ConstraintEnergy

/-
  Three canonical families of examples.
  These are intentionally abstract: the categorical layer should only require
  the energy-decrease property, not the internal analytic proof.
-/

/-- Gradient-flow-style updates: packaged abstractly by an energy-decrease map. -/
def gradientFlowFamily
    (choose :
      ∀ X : ConstraintEnergy.{u},
        Σ' u : X.State → X.State, ∀ x, X.energy (u x) ≤ X.energy x) :
    ConstraintEnergy.DynamicFamily where
  dyn := by
    intro X
    rcases choose X with ⟨u, h⟩
    exact ConstraintEnergy.mkDynamics u h

/-- KL-minimization-style updates: again abstractly packaged by an
energy-decrease witness. -/
def klMinimizationFamily
    (choose :
      ∀ X : ConstraintEnergy.{u},
        Σ' u : X.State → X.State, ∀ x, X.energy (u x) ≤ X.energy x) :
    ConstraintEnergy.DynamicFamily where
  dyn := by
    intro X
    rcases choose X with ⟨u, h⟩
    exact ConstraintEnergy.mkDynamics u h

/-- Relational gauge-flow-style updates: packaged the same way. -/
def relationalGaugeFlowFamily
    (choose :
      ∀ X : ConstraintEnergy.{u},
        Σ' u : X.State → X.State, ∀ x, X.energy (u x) ≤ X.energy x) :
    ConstraintEnergy.DynamicFamily where
  dyn := by
    intro X
    rcases choose X with ⟨u, h⟩
    exact ConstraintEnergy.mkDynamics u h

/-- Therefore each dynamics family yields an endofunctor on the category
of constraint-energy systems. -/
def gradientFlowFunctor
    (choose :
      ∀ X : ConstraintEnergy.{u},
        Σ' u : X.State → X.State, ∀ x, X.energy (u x) ≤ X.energy x) :
    ConstraintEnergy.{u} ⥤ ConstraintEnergy.{u} :=
  (gradientFlowFamily choose).toFunctor

def klMinimizationFunctor
    (choose :
      ∀ X : ConstraintEnergy.{u},
        Σ' u : X.State → X.State, ∀ x, X.energy (u x) ≤ X.energy x) :
    ConstraintEnergy.{u} ⥤ ConstraintEnergy.{u} :=
  (klMinimizationFamily choose).toFunctor

def relationalGaugeFlowFunctor
    (choose :
      ∀ X : ConstraintEnergy.{u},
        Σ' u : X.State → X.State, ∀ x, X.energy (u x) ≤ X.energy x) :
    ConstraintEnergy.{u} ⥤ ConstraintEnergy.{u} :=
  (relationalGaugeFlowFamily choose).toFunctor

/-
  Minimal concrete examples showing the category is inhabited and the
  constructions are non-vacuous.
-/

/-- A one-point energy system. -/
def trivialSystem : ConstraintEnergy where
  State := PUnit
  energy := fun _ => 0

/-- The identity dynamics is energy-preserving, hence energy-decreasing. -/
def trivialChoose :
    ∀ X : ConstraintEnergy.{u},
      Σ' u : X.State → X.State, ∀ x, X.energy (u x) ≤ X.energy x := by
  intro X
  refine ⟨id, ?_⟩
  intro x
  exact le_rfl

/-- Concrete endofunctors. -/
def GF : ConstraintEnergy.{u} ⥤ ConstraintEnergy.{u} :=
  gradientFlowFunctor trivialChoose

def KF : ConstraintEnergy.{u} ⥤ ConstraintEnergy.{u} :=
  klMinimizationFunctor trivialChoose

def RF : ConstraintEnergy.{u} ⥤ ConstraintEnergy.{u} :=
  relationalGaugeFlowFunctor trivialChoose

/-- Sanity check: these functors act as identity on objects in the abstract
packaging used here. -/
@[simp] theorem GF_obj (X : ConstraintEnergy.{u}) : GF.obj X = X := rfl
@[simp] theorem KF_obj (X : ConstraintEnergy.{u}) : KF.obj X = X := rfl
@[simp] theorem RF_obj (X : ConstraintEnergy.{u}) : RF.obj X = X := rfl

/-- The category is nonempty. -/
example : Nonempty ConstraintEnergy := ⟨trivialSystem⟩

end EnergyAsContradiction.CategoryDynamics
